/* === DOINg.AI — Domain Types === */

export type Theme = 'light' | 'dark';
export type Role = 'admin' | 'manager' | 'contributor' | 'viewer';

export enum TaskStatus {
  TODO = 'To Do',
  ONGOING = 'In Progress',
  PAUSED = 'Paused',
  BLOCKED = 'Blocked',
  DONE = 'Done',
}

export enum TaskPriority {
  LOW = 'Low',
  MEDIUM = 'Medium',
  HIGH = 'High',
  URGENT = 'Urgent',
}

export enum ProjectStatus {
  PLANNING = 'Planning',
  ACTIVE = 'Active',
  PAUSED = 'Paused',
  DONE = 'Done',
}

export enum ProjectRole {
  OWNER = 'Owner',
  LEAD = 'Lead',
  CONTRIBUTOR = 'Contributor',
}

export interface User {
  id: string;
  uid: string;                     // login handle (unique)
  /** @deprecated Legacy plaintext password kept only for backwards
   *  compatibility with seed data. Once a user signs in or changes their
   *  password, this is cleared and `passwordHash`+`passwordSalt` take over. */
  password?: string;
  passwordHash?: string;           // PBKDF2-SHA256, base64
  passwordSalt?: string;           // 16-byte salt, base64
  /** When true, the next successful sign-in forces a password change before
   *  the app is reachable. Cleared automatically after the change. */
  mustChangePassword?: boolean;
  firstName: string;
  lastName: string;
  email: string;
  team: string;
  squadTeam?: string;
  functionTitle: string;           // job title / role on org
  role: Role;                      // app-level role
  expectations?: string;
  avatarColor?: string;
  createdAt: string;
}

export interface ChecklistItem {
  id: string;
  text: string;
  done: boolean;
}

export interface AuditEntry {
  id: string;
  date: string;
  userId: string;
  userName: string;
  action: string;
  details?: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  assigneeId?: string;
  originalEta: string;             // ISO date
  currentEta?: string;             // ISO date (when slipped)
  weight: number;                  // 1..10
  dependencies?: string[];
  checklist?: ChecklistItem[];
  isImportant?: boolean;
}

export interface ProjectMember {
  userId: string;
  role: ProjectRole;
}

export interface Milestone {
  id: string;
  label: string;
  date: string;                    // ISO date
  done: boolean;
}

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  tasks: Omit<Task, 'id' | 'assigneeId'>[];
  milestones: Omit<Milestone, 'id'>[];
  tags: string[];
  createdAt: string;
}

export type DevStatus = 'to_start' | 'dev' | 'uat' | 'prod';

export type InnovationStatus = 'poc' | 'pilot' | 'prod';

export interface ExternalMember {
  id: string;
  name: string;
  email?: string;
  role?: string;        // free-text role/function
  company?: string;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  context?: string;
  notes?: string;
  status: ProjectStatus;
  devStatus?: DevStatus;           // dev workflow stage
  innovationStatus?: InnovationStatus; // innovation maturity stage
  managerId?: string;              // user id of owner/PM
  startDate: string;
  deadline: string;
  initialDeadline?: string;
  isImportant?: boolean;
  isArchived?: boolean;
  botCreated?: boolean;            // set when project was generated by AI bulk import
  budget?: number;
  familyId?: string;
  fteGain?: number;
  confidentiality?: 'public' | 'internal' | 'confidential' | 'restricted';
  members: ProjectMember[];
  externalMembers?: ExternalMember[];   // people outside the contributor list
  tasks: Task[];
  milestones: Milestone[];
  technologyIds: string[];
  repoIds: string[];
  tags: string[];
  auditLog: AuditEntry[];
  presentations?: ProjectPresentation[];
  linkedApps?: ProjectLinkedApp[];
  createdAt: string;
  updatedAt: string;
}

export type TechLayer =
  | 'frontend'
  | 'backend'
  | 'fullstack'
  | 'data'
  | 'ml-ai'
  | 'infrastructure'
  | 'devops'
  | 'mobile'
  | 'security';

export type TechMaturity = 'evaluating' | 'adopted' | 'deprecated' | 'hold';

export interface Technology {
  id: string;
  name: string;
  category: 'framework' | 'library' | 'database' | 'tool' | 'language' | 'service';
  layer?: TechLayer;
  maturityStatus?: TechMaturity;
  description: string;
  version?: string;
  url?: string;
  license?: string;
  internalOwner?: string;
  technicalArchitect?: string;
  tags: string[];
  createdAt: string;
}

export type RepoProvider = 'bitbucket' | 'github' | 'gitlab' | 'azure' | 'other';

export interface Repository {
  id: string;
  name: string;
  provider?: RepoProvider;
  url: string;
  description: string;
  language?: string;
  visibility: 'public' | 'private' | 'internal';
  projectIds: string[];
  createdByUserId?: string;     // owner — used for role-based edit permissions
  createdAt: string;
}

export interface Communication {
  id: string;
  title: string;
  type: 'weekly' | 'newsletter' | 'exco' | 'info';
  subject: string;
  content: string;
  mailingListIds: string[];
  projectIds: string[];
  authorId: string;
  status: 'draft' | 'sent';
  sentAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MailingList {
  id: string;
  name: string;
  description?: string;
  emails: string[];
  createdAt: string;
}

export interface EmailTemplate {
  id: string;
  name: string;
  type: 'weekly' | 'newsletter' | 'exco' | 'info';
  subject: string;
  content: string;
  createdAt: string;
}

export interface WeeklyCheckIn {
  id: string;
  userId: string;
  weekOf: string;                  // ISO date of Monday
  accomplishments: string;
  blockers: string;
  nextSteps: string;
  mood: 'green' | 'amber' | 'red';
  createdAt: string;
  updatedAt: string;
}

export interface AppNotification {
  id: string;
  type: 'stale_project' | 'task_slipping' | 'report_overdue' | 'milestone_reached' | 'info';
  message: string;
  details?: string;
  targetUserId?: string;
  targetRole?: Role;
  relatedId?: string;
  createdAt: string;
  seenBy: string[];
}

export interface LlmConfig {
  provider: 'ollama' | 'openai_compatible' | 'n8n';
  baseUrl: string;
  apiKey?: string;
  model: string;
  systemPrompt: string;
}

/* === Hackathon === */

export type HackathonStatus = 'upcoming' | 'active' | 'completed' | 'archived';
export type HackathonRole = 'dev' | 'sme' | 'expert' | 'pm' | 'designer' | 'other';
export type HackathonDocType = 'brief' | 'guide' | 'result' | 'presentation' | 'resource' | 'other';

export interface HackathonParticipant {
  id: string;
  name: string;
  role: HackathonRole;
  email?: string;
  team?: string;
  expertise?: string;
}

export interface HackathonDocument {
  id: string;
  title: string;
  type: HackathonDocType;
  content: string;
  authorId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface HackathonMessage {
  id: string;
  authorId: string;
  authorName: string;
  content: string;
  createdAt: string;
}

export interface Hackathon {
  id: string;
  title: string;
  theme: string;
  objective: string;
  challenge?: string;
  status: HackathonStatus;
  startDate: string;
  endDate: string;
  location?: string;
  participants: HackathonParticipant[];
  documents: HackathonDocument[];
  messages: HackathonMessage[];
  results?: string;
  aiSynthesis?: string;
  tags: string[];
  createdByUserId?: string;     // owner — used for role-based edit permissions
  createdAt: string;
  updatedAt: string;
}

// Smart ToDo
export type TodoStatus = 'todo' | 'in_progress' | 'blocked' | 'done' | 'cancelled';
export type TodoPriorityLevel = 'low' | 'medium' | 'high' | 'urgent';
export type EnergyLevel = 'low' | 'medium' | 'high';
export type PlanningPeriod = 'today' | 'tomorrow' | 'this_week' | 'this_month' | 'this_quarter' | 'this_year' | 'tbd';

export interface TodoAttachment {
  name: string;
  url: string;
}

export interface SmartTodo {
  id: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  source: string;
  requester: string;
  sponsor?: string;
  isRecurring: boolean;
  recurrenceRule: string | null;
  createdByBot?: boolean;
  isArchived?: boolean;
  managerAssigned?: boolean;
  assignedByUserId?: string;
  title: string;
  description: string;
  tags: string[];
  attachments: TodoAttachment[];
  links: string[];
  status: TodoStatus;
  priorityLevel: TodoPriorityLevel;
  eisenhowerQuadrant: 1 | 2 | 3 | 4 | null;
  energyRequired: EnergyLevel;
  estimatedDurationMin: number | null;
  actualTimeSpentMin: number | null;
  startDate: string | null;
  dueDate: string | null;
  completedAt: string | null;
  planningFor?: PlanningPeriod | null;
  scheduledDateTime?: string | null;
  scheduledDuration?: number | null;
}

export interface ProjectPresentation {
  id: string;
  name: string;
  url: string;
  addedAt: string;
  addedByUserId: string;
}

export interface ProjectLinkedApp {
  id: string;
  name: string;
  role: 'impacted' | 'contributor' | 'both';
  description?: string;
  url?: string;
}

export interface ProjectFamily {
  id: string;
  name: string;
  description?: string;
  color?: string; // hex color for visual identity
  createdAt: string;
}

export interface McpTool {
  name: string;
  description: string;
  enrichedDescription?: string; // LLM-enriched version
}

export type McpDeployStatus = 'dev' | 'uat' | 'production';

export interface McpFamily {
  id: string;
  name: string;
  description?: string;
  color: string;   // hex colour, used as accent in the UI
  createdAt: string;
}

export type McpRecommendationSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface McpCodeRecommendation {
  id: string;
  text: string;
  category?: string;                       // "Security", "Performance", "Reliability"…
  severity?: McpRecommendationSeverity;
  done: boolean;                           // checkable in the UI
  fixedAt?: string;                        // ISO date when marked done
  fixedBy?: string;                        // userId
}

export interface McpCodeAnalysis {
  summary: string;                         // overall AI-generated review in English
  recommendations: McpCodeRecommendation[];
  language?: string;                       // detected language
  analyzedAt: string;                      // ISO
  analyzedBy?: string;                     // userId
  inputSize?: number;                      // chars of input analyzed
}

export type McpBestPracticeSource = 'manual' | 'ai_generated' | 'ai_rephrased' | 'synthesized';

export interface McpBestPractice {
  id: string;
  title: string;
  content: string;                         // Markdown
  source: McpBestPracticeSource;
  category?: string;                       // "Security", "Reliability", "DevX"…
  tags: string[];
  pinned?: boolean;                        // pin to top
  appliesTo?: string[];                    // optional list of McpServer ids this practice applies to
  createdAt: string;
  updatedAt: string;
}

export interface McpServer {
  id: string;
  name: string;
  description: string;
  enrichedDescription?: string;
  url?: string;
  token?: string;
  source: 'declarative' | 'url';
  tools: McpTool[];
  category?: string;            // "Productivity", "Data", "Dev Tools"…
  tags: string[];
  isActive: boolean;

  // ── Extended metadata ────────────────────────────────────────────────
  familyId?: string;            // links to McpFamily
  scope?: string;               // e.g. "Internal", "External", "Cross-team"
  originData?: string;          // e.g. "Internal DB", "Public API", "Partner feed"
  dataScope?: string;           // e.g. "Finance", "HR", "All", "Europe"
  dataSourceUsed?: string;      // concrete sources: "PostgreSQL", "Salesforce"…
  useCase?: string;             // free-text use-case description
  teamIT?: string;              // IT team responsible
  userTeams?: string[];         // business teams using this server
  deployStatus?: McpDeployStatus;

  // ── AI Code Analysis (stored per server) ─────────────────────────────
  codeAnalysis?: McpCodeAnalysis;

  createdByUserId?: string;     // owner — used for role-based edit permissions
  createdAt: string;
  updatedAt: string;
}

/* === AI Agents — internal agent tracking (development → production) ===
 *
 * Designed to mirror the MCP Hub pattern (family grouping, deploy status,
 * tools, teams) but adds AI-specific fields: model, framework, system prompt,
 * version history, and operational metrics.
 */

export type AgentStatus = 'idea' | 'design' | 'dev' | 'testing' | 'production' | 'deprecated';
export type AgentFramework = 'langchain' | 'llamaindex' | 'crewai' | 'autogen' | 'custom' | 'n8n' | 'other';
export type AgentToolSource = 'native' | 'mcp' | 'custom';

export interface AgentTool {
  name: string;
  description: string;
  source?: AgentToolSource;
  mcpServerId?: string;   // optional link to an MCP server (when source = 'mcp')
}

export interface AgentRelease {
  version: string;          // ex: "1.0.0"
  date: string;             // ISO
  notes: string;            // changelog
  authorUserId?: string;
}

export interface AgentEvaluation {
  id: string;
  date: string;             // ISO
  testSetName: string;      // ex: "Q4 regression set"
  score: number;            // 0-100
  notes?: string;
  authorUserId?: string;
}

export interface AgentMetrics {
  avgResponseTimeMs?: number;
  successRatePct?: number;
  monthlyInvocations?: number;
  costPerMonthEur?: number;
  userSatisfaction?: number;  // 0-5
  lastEvaluatedAt?: string;   // ISO
}

export interface AgentFamily {
  id: string;
  name: string;
  description?: string;
  color: string;            // hex, used everywhere for visual grouping
  createdAt: string;
}

export interface Agent {
  id: string;
  name: string;
  description: string;
  enrichedDescription?: string;

  // Identity & classification
  category?: string;        // ex: "Customer Support", "Data Analysis", "DevOps"
  familyId?: string;
  tags: string[];

  // Lifecycle
  status: AgentStatus;
  isActive: boolean;
  version: string;          // current version, ex: "1.0.0"

  // Technical stack
  llmProvider?: string;     // OpenAI, Anthropic, Ollama, Mistral, …
  llmModel?: string;        // ex: "gpt-4o", "claude-haiku-4-5", "llama3"
  framework?: AgentFramework;
  systemPrompt?: string;
  contextWindow?: number;   // tokens

  // Capabilities
  tools: AgentTool[];
  mcpServerIds: string[];   // MCP servers this agent depends on
  knowledgeBases: string[]; // RAG sources (free-text)

  // Ownership & adoption
  ownerUserId?: string;
  teamIT?: string;
  userTeams: string[];

  // Operations
  metrics?: AgentMetrics;
  releases: AgentRelease[];
  evaluations: AgentEvaluation[];

  // Documentation
  repoUrl?: string;         // link to source repo (if internal)
  docsUrl?: string;         // link to external documentation

  createdAt: string;
  updatedAt: string;
}

/* ============================================================
   Wish List — collective backlog of needs / ideas
   ============================================================
   Open to every signed-in user. Each wish documents a request
   tied to a project, MCP, agent, data feed, or generic feature,
   with sponsor + dates + lifecycle status.
*/

export type WishCategory =
  | 'project'
  | 'mcp'
  | 'agent'
  | 'datafeed'
  | 'feature'
  | 'integration'
  | 'other';

export type WishStatus =
  | 'submitted'      // freshly created
  | 'under_review'   // being triaged
  | 'accepted'       // approved, to be scheduled
  | 'in_progress'    // work started
  | 'done'           // delivered
  | 'rejected'       // declined
  | 'on_hold';       // parked

export type WishPriority = 'low' | 'medium' | 'high' | 'urgent';

export interface WishComment {
  id: string;
  authorUserId: string;
  authorName: string;
  text: string;
  createdAt: string;
}

export interface WishItem {
  id: string;
  title: string;
  description: string;             // free-text explanation of the need
  category: WishCategory;

  // Justification & impact
  businessJustification?: string;  // why this matters
  expectedImpact?: string;         // benefits, gains, FTE saved…

  // People
  requesterId: string;             // auto = submitter
  sponsorId?: string;              // internal sponsor (user id)
  sponsorName?: string;            // free-text sponsor (external or unmapped)

  // Cross-links to existing entities
  relatedProjectId?: string;
  relatedMcpServerId?: string;
  relatedAgentId?: string;
  relatedDataFeedId?: string;
  externalLinks?: string[];        // arbitrary URLs (Confluence, JIRA…)

  // Lifecycle
  status: WishStatus;
  priority: WishPriority;
  wishedDate?: string;             // ETA wished for (ISO date)

  // Triage feedback (set by admin/sponsor)
  reviewNotes?: string;
  decidedAt?: string;
  decidedByUserId?: string;

  comments: WishComment[];
  tags: string[];

  createdAt: string;
  updatedAt: string;
}

export interface AppState {
  users: User[];
  projects: Project[];
  projectTemplates: ProjectTemplate[];
  projectFamilies: ProjectFamily[];
  technologies: Technology[];
  repositories: Repository[];
  communications: Communication[];
  emailTemplates: EmailTemplate[];
  mailingLists: MailingList[];
  weeklyCheckIns: WeeklyCheckIn[];
  notifications: AppNotification[];
  hackathons: Hackathon[];
  workingGroups: WorkingGroup[];
  smartTodos: SmartTodo[];
  mcpServers: McpServer[];
  mcpFamilies: McpFamily[];
  mcpBestPractices: McpBestPractice[];
  agents: Agent[];
  agentFamilies: AgentFamily[];
  wishes: WishItem[];
  llmConfig: LlmConfig;
  prompts: Record<string, string>;
  theme: Theme;
  currentUserId: string | null;
  lastUpdated: number;
}

/* === Working Groups === */

export type WGStatus = 'active' | 'paused' | 'closed';
export type WGMemberRole = 'lead' | 'contributor' | 'observer';
export type WGTaskStatus = 'todo' | 'doing' | 'review' | 'done';
export type WGTaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type WGActionStatus = 'todo' | 'ongoing' | 'blocked' | 'done';

export interface WGActionItem {
  id: string;
  text: string;
  ownerId?: string;
  dueDate?: string;
  status: WGActionStatus;
  carriedFromSessionId?: string;
}

export interface WGMember {
  userId: string;
  role: WGMemberRole;
}

export interface WGTask {
  id: string;
  title: string;
  description?: string;
  status: WGTaskStatus;
  priority: WGTaskPriority;
  assigneeId?: string;
  dueDate?: string;
  labels?: string[];
  checklist?: ChecklistItem[];
  createdAt: string;
  updatedAt: string;
}

export interface WGMeetingNote {
  id: string;
  date: string;
  title: string;
  attendeeIds: string[];
  agenda?: string;
  notes: string;
  decisions: string[];
  actionItems?: WGActionItem[];
  createdAt: string;
  updatedAt: string;
}

export interface WorkingGroup {
  id: string;
  name: string;
  description: string;
  objective: string;
  status: WGStatus;
  ownerId?: string;
  members: WGMember[];
  tasks: WGTask[];
  meetings: WGMeetingNote[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
}
